deploy backend wf fixed tf imports

diff --git a/.github/workflows/deploy-backend.yml b/.github/workflows/deploy-backend.yml
--- a/.github/workflows/deploy-backend.yml
+++ b/.github/workflows/deploy-backend.yml
@@ -78,11 +78,7 @@ jobs:
 
       - name: Terraform Import Lambda Function
         working-directory: terraform/deploy-backend
-        run: terraform import -input=false -var-file=ci.auto.tfvars aws_lambda_function.stock_data_to_dynamo $MSS_BACKEND_LAMBDA_NAME || true
-
-      - name: Terraform Import Ticks Table
-        working-directory: terraform/deploy-backend
-        run: terraform import -input=false -var-file=ci.auto.tfvars aws_dynamodb_table.m7_ticks $TICKS_TABLE || true
+        run: terraform import -input=false -var-file=ci.auto.tfvars aws_lambda_function.mss_backend_lambda $MSS_BACKEND_LAMBDA_NAME || true
 
       - name: Terraform Import Lambda Exec Role
         working-directory: terraform/deploy-backend
@@ -90,16 +86,16 @@ jobs:
 
       - name: Terraform Import Lambda Permission
         working-directory: terraform/deploy-backend
-        run: terraform import -input=false -var-file=ci.auto.tfvars aws_lambda_permission.allow_s3 ${MSS_BACKEND_LAMBDA_NAME}/AllowExecutionFromS3 || true
+        run: terraform import -input=false -var-file=ci.auto.tfvars aws_lambda_permission.apigw_invoke ${MSS_BACKEND_LAMBDA_NAME}/AllowAPIGatewayInvoke || true
 
       - name: Terraform Import Lambda Policy
         working-directory: terraform/deploy-backend
         run: |
-          POLICY_ARN=$(aws iam list-policies --scope Local --query "Policies[?PolicyName=='m7_lambda_policy'].Arn" --output text)
+          POLICY_ARN=$(aws iam list-policies --scope Local --query "Policies[?PolicyName=='mss_backend_lambda_policy'].Arn" --output text)
           if [ -n "$POLICY_ARN" ]; then
-            terraform import -input=false -var-file=ci.auto.tfvars aws_iam_policy.lambda_policy $POLICY_ARN || true
+            terraform import -input=false -var-file=ci.auto.tfvars aws_iam_policy.mss_backend_lambda_policy $POLICY_ARN || true
           else
-            echo "Policy m7_lambda_policy not found, skipping import."
+            echo "Policy mss_backend_lambda_policy not found, skipping import."
           fi
 
       - name: Terraform apply
